"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Calculator, ClipboardCheck, Eye, Gauge, Leaf, Pencil, Plus, Recycle, Trash2, Zap } from "lucide-react";
import { EnvironmentalActionDetail } from "@/components/environmental-impact/EnvironmentalActionDetail";
import { EnvironmentalActionForm } from "@/components/environmental-impact/EnvironmentalActionForm";
import { EnvironmentalReviewPanel } from "@/components/environmental-impact/EnvironmentalReviewPanel";
import { ConfirmDialog } from "@/components/common/ConfirmDialog";
import { EmptyState } from "@/components/common/EmptyState";
import { ErrorState } from "@/components/common/ErrorState";
import { LoadingState } from "@/components/common/LoadingState";
import { useToast } from "@/components/common/ToastProvider";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { calculateEnvironmentalAction, createEnvironmentalAction, deleteEnvironmentalAction, getEnvironmentalActions, getEnvironmentalMethodologies, getEnvironmentalSummary, reviewEnvironmentalAction, submitEnvironmentalReview, updateEnvironmentalAction } from "@/lib/api/environmental";
import { getEventSessions } from "@/lib/api/eventSessions";
import { canDeleteEnvironmentalActions, canManageEnvironmentalActions, canReviewEnvironmentalActions } from "@/lib/permissions";
import type { EnvironmentalAction, EnvironmentalActionInput, EnvironmentalMethodology, EnvironmentalReviewDecision, EnvironmentalSummary } from "@/types/environmental";
import type { EventSession } from "@/types/eventSession";
import type { UserRole } from "@/types/roles";

const labels: Record<string, string> = { ELECTRIC_LIGHTING_TOWER: "Torre eléctrica", ELECTRIC_MOTORCYCLE: "Moto eléctrica", ELECTRIC_CART: "Carrito eléctrico", SOLAR_ENERGY: "Energía solar", ELECTRIC_VEHICLE: "Vehículo eléctrico", BIKE_MOBILITY: "Bicicleta", PUBLIC_TRANSPORT: "Transporte público", OTHER: "Otra acción" };
const statuses: Record<string, string> = { INCOMPLETE: "Incompleto", READY_TO_CALCULATE: "Listo para calcular", CALCULATED: "Calculado", MISSING_METHODOLOGY: "Falta metodología", NEEDS_REVIEW: "Requiere revisión" };
const reviewStatuses: Record<string, { label: string; className: string }> = { DRAFT: { label: "Borrador", className: "bg-slate-100 text-slate-700" }, IN_REVIEW: { label: "En revisión", className: "bg-amber-100 text-amber-800" }, APPROVED: { label: "Aprobado", className: "bg-emerald-100 text-emerald-800" }, CHANGES_REQUESTED: { label: "Con observaciones", className: "bg-orange-100 text-orange-800" }, REJECTED: { label: "Rechazado", className: "bg-red-100 text-red-700" } };
const formatNumber = (value: string, maximumFractionDigits = 6) => new Intl.NumberFormat("es-CL", { maximumFractionDigits }).format(Number(value));
const format = (value: string | null, unit: string) => value === null ? "No calculado" : `${formatNumber(value, 2)} ${unit}`;

export function EnvironmentalImpactTab({ eventId, role }: { eventId: string; role?: UserRole | null }) {
  const [section, setSection] = useState<"summary" | "actions" | "methodology" | "equivalences">("summary"); const [scopeSessionId, setScopeSessionId] = useState(""); const [summary, setSummary] = useState<EnvironmentalSummary | null>(null); const [actions, setActions] = useState<EnvironmentalAction[]>([]); const [sessions, setSessions] = useState<EventSession[]>([]); const [methodologies, setMethodologies] = useState<EnvironmentalMethodology[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [formAction, setFormAction] = useState<EnvironmentalAction | null | undefined>(); const [detailAction, setDetailAction] = useState<EnvironmentalAction | null>(null); const [reviewAction, setReviewAction] = useState<EnvironmentalAction | null>(null); const [deleting, setDeleting] = useState<EnvironmentalAction | null>(null); const { toast } = useToast();
  const load = useCallback(async () => { setLoading(true); setError(null); try { const selectedSession = scopeSessionId || undefined; const [s, a, shows, methods] = await Promise.all([getEnvironmentalSummary(eventId, selectedSession), getEnvironmentalActions(eventId, selectedSession), getEventSessions(eventId), getEnvironmentalMethodologies()]); setSummary(s); setActions(a.items); setSessions(shows); setMethodologies(methods); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo cargar Impacto Ambiental."); } finally { setLoading(false); } }, [eventId, scopeSessionId]);
  useEffect(() => { void load(); }, [load]); const showNames = useMemo(() => Object.fromEntries(sessions.map((s) => [s.id, s.name])), [sessions]);
  async function save(value: EnvironmentalActionInput) { setSaving(true); try { if (formAction) await updateEnvironmentalAction(eventId, formAction.id, value); else await createEnvironmentalAction(eventId, value); setFormAction(undefined); toast({ tone: "success", title: formAction ? "Acción actualizada" : "Acción registrada", description: "El registro quedó disponible para cálculo." }); await load(); } catch (err) { toast({ tone: "error", title: "No se pudo guardar", description: err instanceof Error ? err.message : undefined }); } finally { setSaving(false); } }
  async function calculate(item: EnvironmentalAction) { try { await calculateEnvironmentalAction(eventId, item.id); toast({ tone: "success", title: "Cálculo actualizado", description: "Factores y entradas quedaron congelados en el snapshot." }); await load(); } catch (err) { toast({ tone: "error", title: "No se pudo calcular", description: err instanceof Error ? err.message : undefined }); } }
  async function remove() { if (!deleting) return; setSaving(true); try { await deleteEnvironmentalAction(eventId, deleting.id); setDeleting(null); toast({ tone: "success", title: "Acción eliminada" }); await load(); } finally { setSaving(false); } }
  async function submitReview() { if (!reviewAction) return; setSaving(true); try { await submitEnvironmentalReview(eventId, reviewAction.id); setReviewAction(null); toast({ tone: "success", title: "Acción enviada a revisión", description: "Un administrador ya puede validarla." }); await load(); } catch (err) { toast({ tone: "error", title: "No se pudo enviar", description: err instanceof Error ? err.message : undefined }); } finally { setSaving(false); } }
  async function review(decision: EnvironmentalReviewDecision, comment?: string) { if (!reviewAction) return; setSaving(true); try { await reviewEnvironmentalAction(eventId, reviewAction.id, decision, comment); setReviewAction(null); toast({ tone: "success", title: decision === "APPROVED" ? "Impacto aprobado" : "Revisión registrada" }); await load(); } catch (err) { toast({ tone: "error", title: "No se pudo registrar la revisión", description: err instanceof Error ? err.message : undefined }); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Cargando impacto ambiental..." />; if (error) return <ErrorState message={error} onRetry={load} />;
  const cards = [{ label: "CO₂e evitado", value: format(summary?.co2e_avoided_kg ?? null, "kg"), icon: Leaf }, { label: "Combustible evitado", value: format(summary?.fuel_avoided_l ?? null, "L"), icon: Recycle }, { label: "Energía utilizada", value: format(summary?.energy_kwh ?? null, "kWh"), icon: Zap }, { label: "PM2.5 evitado", value: format(summary?.pm25_avoided_kg ?? null, "kg"), icon: Gauge }, { label: "PM10 evitado", value: format(summary?.pm10_avoided_kg ?? null, "kg"), icon: Gauge }, { label: "NOx evitado", value: format(summary?.nox_avoided_kg ?? null, "kg"), icon: Gauge }];
  return <div className="space-y-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-xl font-bold">Impacto Ambiental</h2><p className="text-sm text-slate-600">Impacto evitado frente a una línea base documentada. Es independiente de Huella.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="text-xs font-semibold text-slate-600">Alcance mostrado<select aria-label="Alcance mostrado" className="mt-1 h-10 min-w-64 rounded-xl border bg-white px-3 text-sm" value={scopeSessionId} onChange={(e) => setScopeSessionId(e.target.value)}><option value="">Evento completo · todos los alcances</option>{sessions.filter((item) => !item.archived_at).map((item) => <option key={item.id} value={item.id}>Solo show · {item.name}</option>)}</select></label>{canManageEnvironmentalActions(role) ? <Button className="self-end" onClick={() => setFormAction(null)}><Plus className="h-4 w-4" />Registrar equipo o acción</Button> : null}</div></div><div className="flex gap-2 overflow-x-auto">{([ ["summary", "Resumen"], ["actions", "Equipos y acciones"], ["methodology", "Metodología"], ["equivalences", "Equivalencias"] ] as const).map(([key, label]) => <Button key={key} variant={section === key ? "primary" : "secondary"} onClick={() => setSection(key)}>{label}</Button>)}</div>
    {section === "summary" ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent><Icon className="h-5 w-5 text-emerald-700" /><p className="mt-3 text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p>{value === "No calculado" ? <p className="mt-1 text-xs text-amber-700">Factor o metodología pendiente</p> : null}</CardContent></Card>)}</div><p className="text-sm text-slate-500">{summary?.actions_count ?? 0} acciones registradas. Cero se muestra solo cuando fue realmente calculado.</p></> : null}
    {section === "actions" ? actions.length === 0 ? <EmptyState title="Aún no hay acciones ambientales" description="Registra el uso real de una solución sostenible para comenzar." action={canManageEnvironmentalActions(role) ? <Button onClick={() => setFormAction(null)}>Registrar primera acción</Button> : undefined} /> : <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-left"><tr>{["Equipo/acción", "Alcance", "Cantidad", "Cálculo", "Validación", "CO₂e evitado", "Actualización", "Acciones"].map((h) => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{actions.map((item) => { const co2 = item.metrics.find((m) => m.metric_key === "CO2E_AVOIDED_KG")?.value ?? null; const reviewState = reviewStatuses[item.review_status]; return <tr className="border-t" key={item.id}><td className="p-3"><b>{item.name}</b><p className="text-xs text-slate-500">{labels[item.action_type]}</p></td><td className="p-3">{item.session_id ? showNames[item.session_id] || "Show" : "Evento completo"}</td><td className="p-3">{formatNumber(item.quantity_used, 4)}</td><td className="p-3">{statuses[item.status]}</td><td className="p-3"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${reviewState.className}`}>{reviewState.label}</span></td><td className="p-3">{format(co2, "kg")}</td><td className="p-3">{new Date(item.updated_at).toLocaleDateString("es-CL")}</td><td className="p-3"><div className="flex gap-1"><Button aria-label="Ver detalle" size="sm" variant="ghost" onClick={() => setDetailAction(item)}><Eye className="h-4 w-4" /></Button><Button aria-label="Abrir revisión" size="sm" variant="ghost" onClick={() => setReviewAction(item)}><ClipboardCheck className="h-4 w-4" /></Button>{canManageEnvironmentalActions(role) ? <><Button aria-label="Editar" size="sm" variant="ghost" onClick={() => setFormAction(item)}><Pencil className="h-4 w-4" /></Button><Button size="sm" variant="secondary" disabled={item.status === "MISSING_METHODOLOGY"} onClick={() => void calculate(item)}><Calculator className="h-4 w-4" />Calcular</Button></> : null}{canDeleteEnvironmentalActions(role) ? <Button aria-label="Eliminar" size="sm" variant="ghost" onClick={() => setDeleting(item)}><Trash2 className="h-4 w-4" /></Button> : null}</div></td></tr>; })}</tbody></table></div> : null}
    {section === "methodology" ? methodologies.length ? <div className="grid gap-3 lg:grid-cols-2">{methodologies.map((m) => <Card key={m.id}><CardContent><p className="font-bold">{m.name}</p><p className="mt-1 text-sm text-slate-600">Línea base: {m.baseline_technology}</p><p className="text-sm text-slate-600">Escenario real: {m.actual_technology}</p><p className="mt-3 text-sm">{m.description}</p></CardContent></Card>)}</div> : <EmptyState title="Metodologías pendientes" description="Un administrador debe configurar una línea base y factores documentados antes de calcular." /> : null}
    {section === "equivalences" ? summary?.equivalences.length ? <><div className="grid gap-3 lg:grid-cols-2">{summary.equivalences.map((e) => <Card key={e.id}><CardContent><p className="text-sm text-slate-500">{e.name}</p><p className="mt-2 text-2xl font-bold text-emerald-800">{formatNumber(e.value, 3)} {e.unit.replace(/\/kgCO2e$/, "")}</p><p className="mt-2 text-xs text-slate-500">Calculado desde {format(e.source_value, "kg CO2e")} × {formatNumber(e.factor, 10)}. {e.source} · {e.year}</p></CardContent></Card>)}</div><p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Estas equivalencias son referencias comunicacionales. No representan compensaciones ni certificaciones ambientales.</p></> : <EmptyState title="Sin equivalencias calculables" description="Aparecerán cuando exista una métrica calculada y una equivalencia activa y documentada para ella." /> : null}
    {detailAction ? <EnvironmentalActionDetail action={detailAction} showName={detailAction.session_id ? showNames[detailAction.session_id] : undefined} onClose={() => setDetailAction(null)} /> : null}{reviewAction ? <EnvironmentalReviewPanel eventId={eventId} action={reviewAction} canManage={canManageEnvironmentalActions(role)} canReview={canReviewEnvironmentalActions(role)} busy={saving} onClose={() => setReviewAction(null)} onSubmit={submitReview} onReview={review} /> : null}{formAction !== undefined ? <EnvironmentalActionForm action={formAction} methodologies={methodologies} saving={saving} sessions={sessions} onClose={() => setFormAction(undefined)} onSave={save} /> : null}<ConfirmDialog open={Boolean(deleting)} title="Eliminar acción ambiental" description="Se eliminarán también sus métricas y snapshots. Esta acción quedará auditada." confirmLabel="Eliminar" loading={saving} onClose={() => setDeleting(null)} onConfirm={() => void remove()} /></div>;
}
