"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Calculator, Gauge, Leaf, Pencil, Plus, Recycle, Trash2, Zap } from "lucide-react";
import { EnvironmentalActionForm } from "@/components/environmental-impact/EnvironmentalActionForm";
import { ConfirmDialog } from "@/components/common/ConfirmDialog";
import { EmptyState } from "@/components/common/EmptyState";
import { ErrorState } from "@/components/common/ErrorState";
import { LoadingState } from "@/components/common/LoadingState";
import { useToast } from "@/components/common/ToastProvider";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { calculateEnvironmentalAction, createEnvironmentalAction, deleteEnvironmentalAction, getEnvironmentalActions, getEnvironmentalEquivalences, getEnvironmentalMethodologies, getEnvironmentalSummary, updateEnvironmentalAction } from "@/lib/api/environmental";
import { getEventSessions } from "@/lib/api/eventSessions";
import { canDeleteEnvironmentalActions, canManageEnvironmentalActions } from "@/lib/permissions";
import type { EnvironmentalAction, EnvironmentalActionInput, EnvironmentalMethodology, EnvironmentalSummary } from "@/types/environmental";
import type { EventSession } from "@/types/eventSession";
import type { UserRole } from "@/types/roles";

const labels: Record<string, string> = { ELECTRIC_LIGHTING_TOWER: "Torre eléctrica", ELECTRIC_MOTORCYCLE: "Moto eléctrica", ELECTRIC_CART: "Carrito eléctrico", SOLAR_ENERGY: "Energía solar", ELECTRIC_VEHICLE: "Vehículo eléctrico", BIKE_MOBILITY: "Bicicleta", PUBLIC_TRANSPORT: "Transporte público", OTHER: "Otra acción" };
const statuses: Record<string, string> = { INCOMPLETE: "Incompleto", READY_TO_CALCULATE: "Listo para calcular", CALCULATED: "Calculado", MISSING_METHODOLOGY: "Falta metodología", NEEDS_REVIEW: "Requiere revisión" };
const format = (value: string | null, unit: string) => value === null ? "No calculado" : `${new Intl.NumberFormat("es-CL", { maximumFractionDigits: 2 }).format(Number(value))} ${unit}`;

export function EnvironmentalImpactTab({ eventId, role }: { eventId: string; role?: UserRole | null }) {
  const [section, setSection] = useState<"summary" | "actions" | "methodology" | "equivalences">("summary"); const [summary, setSummary] = useState<EnvironmentalSummary | null>(null); const [actions, setActions] = useState<EnvironmentalAction[]>([]); const [sessions, setSessions] = useState<EventSession[]>([]); const [methodologies, setMethodologies] = useState<EnvironmentalMethodology[]>([]); const [equivalences, setEquivalences] = useState<Array<{id: string; name: string; source: string; year: number; unit: string}>>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [formAction, setFormAction] = useState<EnvironmentalAction | null | undefined>(); const [deleting, setDeleting] = useState<EnvironmentalAction | null>(null); const { toast } = useToast();
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [s, a, shows, methods, eq] = await Promise.all([getEnvironmentalSummary(eventId), getEnvironmentalActions(eventId), getEventSessions(eventId), getEnvironmentalMethodologies(), getEnvironmentalEquivalences()]); setSummary(s); setActions(a.items); setSessions(shows); setMethodologies(methods); setEquivalences(eq); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo cargar Impacto Ambiental."); } finally { setLoading(false); } }, [eventId]);
  useEffect(() => { void load(); }, [load]); const showNames = useMemo(() => Object.fromEntries(sessions.map((s) => [s.id, s.name])), [sessions]);
  async function save(value: EnvironmentalActionInput) { setSaving(true); try { if (formAction) await updateEnvironmentalAction(eventId, formAction.id, value); else await createEnvironmentalAction(eventId, value); setFormAction(undefined); toast({ tone: "success", title: formAction ? "Acción actualizada" : "Acción registrada", description: "El registro quedó disponible para cálculo." }); await load(); } catch (err) { toast({ tone: "error", title: "No se pudo guardar", description: err instanceof Error ? err.message : undefined }); } finally { setSaving(false); } }
  async function calculate(item: EnvironmentalAction) { try { await calculateEnvironmentalAction(eventId, item.id); toast({ tone: "success", title: "Cálculo actualizado", description: "Factores y entradas quedaron congelados en el snapshot." }); await load(); } catch (err) { toast({ tone: "error", title: "No se pudo calcular", description: err instanceof Error ? err.message : undefined }); } }
  async function remove() { if (!deleting) return; setSaving(true); try { await deleteEnvironmentalAction(eventId, deleting.id); setDeleting(null); toast({ tone: "success", title: "Acción eliminada" }); await load(); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Cargando impacto ambiental..." />; if (error) return <ErrorState message={error} onRetry={load} />;
  const cards = [{ label: "CO2e evitado", value: format(summary?.co2e_avoided_kg ?? null, "kg"), icon: Leaf }, { label: "Combustible evitado", value: format(summary?.fuel_avoided_l ?? null, "L"), icon: Recycle }, { label: "Energía utilizada", value: format(summary?.energy_kwh ?? null, "kWh"), icon: Zap }, { label: "PM2.5 evitado", value: format(summary?.pm25_avoided_kg ?? null, "kg"), icon: Gauge }];
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">Impacto Ambiental</h2><p className="text-sm text-slate-600">Impacto evitado frente a una línea base documentada. Es independiente de Huella.</p></div>{canManageEnvironmentalActions(role) ? <Button onClick={() => setFormAction(null)}><Plus className="h-4 w-4" />Registrar equipo o acción</Button> : null}</div><div className="flex gap-2 overflow-x-auto">{([ ["summary", "Resumen"], ["actions", "Equipos y acciones"], ["methodology", "Metodología"], ["equivalences", "Equivalencias"] ] as const).map(([key, label]) => <Button key={key} variant={section === key ? "primary" : "secondary"} onClick={() => setSection(key)}>{label}</Button>)}</div>
    {section === "summary" ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent><Icon className="h-5 w-5 text-emerald-700" /><p className="mt-3 text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p>{value === "No calculado" ? <p className="mt-1 text-xs text-amber-700">Factor o metodología pendiente</p> : null}</CardContent></Card>)}</div><p className="text-sm text-slate-500">{summary?.actions_count ?? 0} acciones registradas. Cero se muestra solo cuando fue realmente calculado.</p></> : null}
    {section === "actions" ? actions.length === 0 ? <EmptyState title="Aún no hay acciones ambientales" description="Registra el uso real de una solución sostenible para comenzar." action={canManageEnvironmentalActions(role) ? <Button onClick={() => setFormAction(null)}>Registrar primera acción</Button> : undefined} /> : <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50 text-left"><tr>{["Equipo/acción", "Alcance", "Cantidad", "Estado", "CO2e evitado", "Actualización", "Acciones"].map((h) => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{actions.map((item) => { const co2 = item.metrics.find((m) => m.metric_key === "CO2E_AVOIDED_KG")?.value ?? null; return <tr className="border-t" key={item.id}><td className="p-3"><b>{item.name}</b><p className="text-xs text-slate-500">{labels[item.action_type]}</p></td><td className="p-3">{item.session_id ? showNames[item.session_id] || "Show" : "Evento completo"}</td><td className="p-3">{item.quantity_used}</td><td className="p-3">{statuses[item.status]}</td><td className="p-3">{format(co2, "kg")}</td><td className="p-3">{new Date(item.updated_at).toLocaleDateString("es-CL")}</td><td className="p-3"><div className="flex gap-1">{canManageEnvironmentalActions(role) ? <><Button aria-label="Editar" size="sm" variant="ghost" onClick={() => setFormAction(item)}><Pencil className="h-4 w-4" /></Button><Button size="sm" variant="secondary" disabled={item.status === "MISSING_METHODOLOGY"} onClick={() => void calculate(item)}><Calculator className="h-4 w-4" />Calcular</Button></> : null}{canDeleteEnvironmentalActions(role) ? <Button aria-label="Eliminar" size="sm" variant="ghost" onClick={() => setDeleting(item)}><Trash2 className="h-4 w-4" /></Button> : null}</div></td></tr>; })}</tbody></table></div> : null}
    {section === "methodology" ? methodologies.length ? <div className="grid gap-3 lg:grid-cols-2">{methodologies.map((m) => <Card key={m.id}><CardContent><p className="font-bold">{m.name}</p><p className="mt-1 text-sm text-slate-600">Línea base: {m.baseline_technology}</p><p className="text-sm text-slate-600">Escenario real: {m.actual_technology}</p><p className="mt-3 text-sm">{m.description}</p></CardContent></Card>)}</div> : <EmptyState title="Metodologías pendientes" description="Un administrador debe configurar una línea base y factores documentados antes de calcular." /> : null}
    {section === "equivalences" ? equivalences.length ? <div className="grid gap-3 lg:grid-cols-2">{equivalences.map((e) => <Card key={e.id}><CardContent><p className="font-bold">{e.name}</p><p className="text-sm text-slate-600">{e.source} · {e.year}</p></CardContent></Card>)}</div> : <EmptyState title="Sin equivalencias configuradas" description="No se mostrarán equivalencias sin un factor activo y documentado." /> : null}
    {formAction !== undefined ? <EnvironmentalActionForm action={formAction} methodologies={methodologies} saving={saving} sessions={sessions} onClose={() => setFormAction(undefined)} onSave={save} /> : null}<ConfirmDialog open={Boolean(deleting)} title="Eliminar acción ambiental" description="Se eliminarán también sus métricas y snapshots. Esta acción quedará auditada." confirmLabel="Eliminar" loading={saving} onClose={() => setDeleting(null)} onConfirm={() => void remove()} /></div>;
}
