from enum import StrEnum


class UserRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    CLIENT = "CLIENT"
    SUPERVISOR = "SUPERVISOR"
    LOGISTICS_OPERATOR = "LOGISTICS_OPERATOR"
    WORKER = "WORKER"


class EventStatus(StrEnum):
    QUOTE = "QUOTE"
    PLANNING = "PLANNING"
    IN_PROGRESS = "IN_PROGRESS"
    FINISHED = "FINISHED"
    REPORT_DELIVERED = "REPORT_DELIVERED"
    CANCELLED = "CANCELLED"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    OBSERVED = "OBSERVED"
    CANCELLED = "CANCELLED"


class IncidentStatus(StrEnum):
    REPORTED = "REPORTED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class PriorityLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class WasteDestination(StrEnum):
    RECYCLING = "RECYCLING"
    COMPOSTING = "COMPOSTING"
    LANDFILL = "LANDFILL"
    RECOVERY = "RECOVERY"
    SPECIAL_DISPOSAL = "SPECIAL_DISPOSAL"
    OTHER = "OTHER"


class CarbonScope(StrEnum):
    SCOPE_1 = "SCOPE_1"
    SCOPE_2 = "SCOPE_2"
    SCOPE_3 = "SCOPE_3"


class SurveyStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class ReportStatus(StrEnum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    DELIVERED = "DELIVERED"
    ARCHIVED = "ARCHIVED"


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    PREPARING = "PREPARING"
    LOADED = "LOADED"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    RETURN_IN_PROGRESS = "RETURN_IN_PROGRESS"
    RETURNED = "RETURNED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class OrderItemStageStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    OBSERVED = "OBSERVED"


class OrderEvidenceStage(StrEnum):
    LOAD = "LOAD"
    DELIVERY = "DELIVERY"
    RETURN = "RETURN"


class InventoryItemType(StrEnum):
    RETURNABLE = "RETURNABLE"
    CONSUMABLE = "CONSUMABLE"
    PARTIAL_CONSUMABLE = "PARTIAL_CONSUMABLE"
    DISPOSABLE = "DISPOSABLE"


class StockMovementType(StrEnum):
    INITIAL_STOCK = "INITIAL_STOCK"
    ADJUSTMENT_IN = "ADJUSTMENT_IN"
    ADJUSTMENT_OUT = "ADJUSTMENT_OUT"
    DAMAGE = "DAMAGE"
    LOSS = "LOSS"
    RECOVER_DAMAGED = "RECOVER_DAMAGED"
    CORRECTION = "CORRECTION"
    PURCHASE_IN = "PURCHASE_IN"
    RESERVE = "RESERVE"
    UNRESERVE = "UNRESERVE"
    OUT_TO_EVENT = "OUT_TO_EVENT"
    RETURN_FROM_EVENT = "RETURN_FROM_EVENT"


class LogisticsOrderStatus(StrEnum):
    REQUESTED = "REQUESTED"
    ASSIGNED = "ASSIGNED"
    STOCK_REVIEW = "STOCK_REVIEW"
    RESERVED = "RESERVED"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    IN_PREPARATION = "IN_PREPARATION"
    LOADED = "LOADED"
    OUT_OF_WAREHOUSE = "OUT_OF_WAREHOUSE"
    DELIVERED = "DELIVERED"
    PARTIALLY_DELIVERED = "PARTIALLY_DELIVERED"
    OUTCOME_PENDING = "OUTCOME_PENDING"
    OUTCOME_RECORDED = "OUTCOME_RECORDED"
    WITH_DIFFERENCES = "WITH_DIFFERENCES"
    CLOSED = "CLOSED"
    OBSERVED = "OBSERVED"
    CANCELLED = "CANCELLED"
