from enum import StrEnum


class UserRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    CLIENT = "CLIENT"
    SUPERVISOR = "SUPERVISOR"
    LOGISTICS_OPERATOR = "LOGISTICS_OPERATOR"
    WORKER = "WORKER"


class LogbookOperationalStage(StrEnum):
    SETUP = "SETUP"
    OPENING = "OPENING"
    OPERATION = "OPERATION"
    CLOSING = "CLOSING"
    DISMANTLING = "DISMANTLING"
    OTHER = "OTHER"


class LogbookTemplateStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class LogbookVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class LogbookAssignmentMode(StrEnum):
    INDIVIDUAL = "INDIVIDUAL"
    SHARED = "SHARED"


class LogbookItemType(StrEnum):
    CHECKBOX = "CHECKBOX"
    YES_NO = "YES_NO"
    STATUS_SELECT = "STATUS_SELECT"
    NUMBER = "NUMBER"
    SHORT_TEXT = "SHORT_TEXT"
    LONG_TEXT = "LONG_TEXT"
    PHOTO = "PHOTO"
    CONFIRMATION = "CONFIRMATION"


class LogbookEvidencePolicy(StrEnum):
    NONE = "NONE"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    REQUIRED_ON_FAILURE = "REQUIRED_ON_FAILURE"


class LogbookInstanceStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    UNDER_REVIEW = "UNDER_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    COMPLETED = "COMPLETED"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"


class LogbookAssignmentStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    RESUBMITTED = "RESUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"


class LogbookResultStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class LogbookRecurrenceFrequency(StrEnum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class LogbookRecurrenceEndMode(StrEnum):
    END_DATE = "END_DATE"
    COUNT = "COUNT"


class LogbookRecurrenceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"


class LogbookRecurrenceExceptionType(StrEnum):
    SKIPPED = "SKIPPED"
    REPROGRAMMED = "REPROGRAMMED"
    NO_VALID_PARTICIPANTS = "NO_VALID_PARTICIPANTS"


class EventStatus(StrEnum):
    QUOTE = "QUOTE"
    PLANNING = "PLANNING"
    IN_PROGRESS = "IN_PROGRESS"
    FINISHED = "FINISHED"
    REPORT_DELIVERED = "REPORT_DELIVERED"
    CANCELLED = "CANCELLED"


class EventSessionStatus(StrEnum):
    PLANNED = "PLANNED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    OBSERVED = "OBSERVED"
    CANCELLED = "CANCELLED"


class IncidentStatus(StrEnum):
    REPORTED = "REPORTED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class PriorityLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class WasteDestination(StrEnum):
    RECYCLING = "RECYCLING"
    COMPOSTING = "COMPOSTING"
    LANDFILL = "LANDFILL"
    RECOVERY = "RECOVERY"
    SPECIAL_DISPOSAL = "SPECIAL_DISPOSAL"
    OTHER = "OTHER"


class CarbonScope(StrEnum):
    SCOPE_1 = "SCOPE_1"
    SCOPE_2 = "SCOPE_2"
    SCOPE_3 = "SCOPE_3"


class EnvironmentalActionType(StrEnum):
    ELECTRIC_LIGHTING_TOWER = "ELECTRIC_LIGHTING_TOWER"
    ELECTRIC_MOTORCYCLE = "ELECTRIC_MOTORCYCLE"
    ELECTRIC_CART = "ELECTRIC_CART"
    SOLAR_ENERGY = "SOLAR_ENERGY"
    ELECTRIC_VEHICLE = "ELECTRIC_VEHICLE"
    BIKE_MOBILITY = "BIKE_MOBILITY"
    PUBLIC_TRANSPORT = "PUBLIC_TRANSPORT"
    OTHER = "OTHER"


class EnvironmentalActionStatus(StrEnum):
    INCOMPLETE = "INCOMPLETE"
    READY_TO_CALCULATE = "READY_TO_CALCULATE"
    CALCULATED = "CALCULATED"
    MISSING_METHODOLOGY = "MISSING_METHODOLOGY"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class EnvironmentalReviewStatus(StrEnum):
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REJECTED = "REJECTED"


class EnvironmentalReviewDecision(StrEnum):
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REJECTED = "REJECTED"
    INVALIDATED = "INVALIDATED"


class EnvironmentalEnergySource(StrEnum):
    MEASURED = "MEASURED"
    CALCULATED = "CALCULATED"
    MANUAL = "MANUAL"


class EnvironmentalEnergyInputMode(StrEnum):
    TOTAL_MEASURED = "TOTAL_MEASURED"
    PER_UNIT_HOUR = "PER_UNIT_HOUR"


class EnvironmentalMetricKey(StrEnum):
    ENERGY_KWH = "ENERGY_KWH"
    FUEL_AVOIDED_L = "FUEL_AVOIDED_L"
    CO2E_BASELINE_KG = "CO2E_BASELINE_KG"
    CO2E_ACTUAL_KG = "CO2E_ACTUAL_KG"
    CO2E_AVOIDED_KG = "CO2E_AVOIDED_KG"
    PM25_BASELINE_KG = "PM25_BASELINE_KG"
    PM25_ACTUAL_KG = "PM25_ACTUAL_KG"
    PM25_AVOIDED_KG = "PM25_AVOIDED_KG"
    PM10_BASELINE_KG = "PM10_BASELINE_KG"
    PM10_ACTUAL_KG = "PM10_ACTUAL_KG"
    PM10_AVOIDED_KG = "PM10_AVOIDED_KG"
    NOX_BASELINE_KG = "NOX_BASELINE_KG"
    NOX_ACTUAL_KG = "NOX_ACTUAL_KG"
    NOX_AVOIDED_KG = "NOX_AVOIDED_KG"


class SurveyStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class EventFormType(StrEnum):
    TRANSPORT_SURVEY = "TRANSPORT_SURVEY"
    STAFF_TRANSPORT_SURVEY = "STAFF_TRANSPORT_SURVEY"
    BIKE_ZONE_REGISTRATION = "BIKE_ZONE_REGISTRATION"
    EXPERIENCE_SURVEY = "EXPERIENCE_SURVEY"
    CUSTOM = "CUSTOM"


class EventFormStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class FormFieldType(StrEnum):
    TEXT = "TEXT"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    NUMBER = "NUMBER"
    TEXTAREA = "TEXTAREA"
    SELECT = "SELECT"
    MULTI_SELECT = "MULTI_SELECT"
    RADIO = "RADIO"
    CHECKBOX = "CHECKBOX"
    DATE = "DATE"
    RATING_1_5 = "RATING_1_5"
    RATING_1_7 = "RATING_1_7"
    YES_NO = "YES_NO"
    FILE = "FILE"


class BikeZoneStatus(StrEnum):
    REGISTERED = "REGISTERED"
    CHECKED_IN = "CHECKED_IN"
    CHECKED_OUT = "CHECKED_OUT"


class ReportStatus(StrEnum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    DELIVERED = "DELIVERED"
    ARCHIVED = "ARCHIVED"


class ReportScope(StrEnum):
    EVENT = "EVENT"
    SHOW = "SHOW"


class ReportSectionType(StrEnum):
    COVER = "COVER"
    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"
    EVENT_INFO = "EVENT_INFO"
    SHOW_INFO = "SHOW_INFO"
    SERVICES = "SERVICES"
    OPERATIONS = "OPERATIONS"
    STAFF = "STAFF"
    TASKS = "TASKS"
    INCIDENTS = "INCIDENTS"
    FORMS = "FORMS"
    BIKE_ZONE = "BIKE_ZONE"
    WASTE = "WASTE"
    CARBON = "CARBON"
    ENVIRONMENTAL_IMPACT = "ENVIRONMENTAL_IMPACT"
    EVIDENCES = "EVIDENCES"
    RECOMMENDATIONS = "RECOMMENDATIONS"
    CONCLUSION = "CONCLUSION"
    CUSTOM = "CUSTOM"


class ReportDataAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    NO_DATA = "NO_DATA"
    EVENT_LEVEL_ONLY = "EVENT_LEVEL_ONLY"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ReportLayoutVariant(StrEnum):
    HERO_IMAGE_TEXT = "HERO_IMAGE_TEXT"
    KPI_GRID = "KPI_GRID"
    TWO_COLUMN = "TWO_COLUMN"
    METRIC_LIST = "METRIC_LIST"
    FEATURE_CHART = "FEATURE_CHART"
    PHOTO_GRID = "PHOTO_GRID"
    EDITORIAL = "EDITORIAL"
    TEXT_IMAGE = "TEXT_IMAGE"
    BIG_NUMBERS = "BIG_NUMBERS"


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    PREPARING = "PREPARING"
    LOADED = "LOADED"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    RETURN_IN_PROGRESS = "RETURN_IN_PROGRESS"
    RETURNED = "RETURNED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class OrderItemStageStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    OBSERVED = "OBSERVED"


class OrderEvidenceStage(StrEnum):
    LOAD = "LOAD"
    DELIVERY = "DELIVERY"
    RETURN = "RETURN"


class InventoryItemType(StrEnum):
    RETURNABLE = "RETURNABLE"
    CONSUMABLE = "CONSUMABLE"
    PARTIAL_CONSUMABLE = "PARTIAL_CONSUMABLE"
    DISPOSABLE = "DISPOSABLE"


class StockMovementType(StrEnum):
    INITIAL_STOCK = "INITIAL_STOCK"
    ADJUSTMENT_IN = "ADJUSTMENT_IN"
    ADJUSTMENT_OUT = "ADJUSTMENT_OUT"
    DAMAGE = "DAMAGE"
    LOSS = "LOSS"
    RECOVER_DAMAGED = "RECOVER_DAMAGED"
    CORRECTION = "CORRECTION"
    PURCHASE_IN = "PURCHASE_IN"
    RESERVE = "RESERVE"
    UNRESERVE = "UNRESERVE"
    OUT_TO_EVENT = "OUT_TO_EVENT"
    RETURN_FROM_EVENT = "RETURN_FROM_EVENT"


class PurchaseRequestStatus(StrEnum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PURCHASED = "PURCHASED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    RECEIVED = "RECEIVED"
    DELIVERED_DIRECT_TO_EVENT = "DELIVERED_DIRECT_TO_EVENT"
    CANCELLED = "CANCELLED"


class PurchaseDeliveryMode(StrEnum):
    TO_WAREHOUSE = "TO_WAREHOUSE"
    DIRECT_TO_EVENT = "DIRECT_TO_EVENT"


class LogisticsEvidenceStage(StrEnum):
    LOGISTICS_PREPARATION = "LOGISTICS_PREPARATION"
    LOGISTICS_LOADING = "LOGISTICS_LOADING"
    LOGISTICS_DISPATCH = "LOGISTICS_DISPATCH"
    LOGISTICS_DELIVERY = "LOGISTICS_DELIVERY"
    LOGISTICS_OUTCOME = "LOGISTICS_OUTCOME"
    LOGISTICS_RETURN = "LOGISTICS_RETURN"
    LOGISTICS_DAMAGED_RETURN = "LOGISTICS_DAMAGED_RETURN"
    LOGISTICS_LOSS = "LOGISTICS_LOSS"
    LOGISTICS_DISCARDED = "LOGISTICS_DISCARDED"
    LOGISTICS_CLOSURE = "LOGISTICS_CLOSURE"
    PURCHASE_REQUEST = "PURCHASE_REQUEST"
    PURCHASE_RECEIPT = "PURCHASE_RECEIPT"
    PURCHASE_WAREHOUSE_RECEIPT = "PURCHASE_WAREHOUSE_RECEIPT"
    PURCHASE_DIRECT_EVENT_DELIVERY = "PURCHASE_DIRECT_EVENT_DELIVERY"
    STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
    STOCK_DAMAGE = "STOCK_DAMAGE"
    STOCK_LOSS = "STOCK_LOSS"
    STOCK_CORRECTION = "STOCK_CORRECTION"


class LogisticsOrderStatus(StrEnum):
    REQUESTED = "REQUESTED"
    ASSIGNED = "ASSIGNED"
    STOCK_REVIEW = "STOCK_REVIEW"
    RESERVED = "RESERVED"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    IN_PREPARATION = "IN_PREPARATION"
    LOADED = "LOADED"
    OUT_OF_WAREHOUSE = "OUT_OF_WAREHOUSE"
    DELIVERED = "DELIVERED"
    PARTIALLY_DELIVERED = "PARTIALLY_DELIVERED"
    OUTCOME_PENDING = "OUTCOME_PENDING"
    OUTCOME_RECORDED = "OUTCOME_RECORDED"
    WITH_DIFFERENCES = "WITH_DIFFERENCES"
    CLOSED = "CLOSED"
    OBSERVED = "OBSERVED"
    CANCELLED = "CANCELLED"


class ReportTemplateKey(StrEnum):
    ENVIRONMENTAL_PREMIUM = "ENVIRONMENTAL_PREMIUM"
    ENVIRONMENTAL_STORY = "ENVIRONMENTAL_STORY"
    BIKE_ZONE = "BIKE_ZONE"
    OPERATIONS = "OPERATIONS"
    EXECUTIVE = "EXECUTIVE"
    COMPLETE = "COMPLETE"


class ReportPublicationStatus(StrEnum):
    GENERATED = "GENERATED"
    DELIVERED = "DELIVERED"
    ARCHIVED = "ARCHIVED"
