"use client";
import { useCallback, useEffect, useState } from "react"; import Link from "next/link"; import { useRouter, useSearchParams } from "next/navigation"; import { Camera } from "lucide-react";
import { EmptyState } from "@/components/common/EmptyState"; import { ErrorState } from "@/components/common/ErrorState"; import { LoadingState } from "@/components/common/LoadingState"; import { useToast } from "@/components/common/ToastProvider"; import { RoleGuard } from "@/components/layout/RoleGuard"; import { MobileConsumptionForm } from "@/components/operations/MobileConsumptionForm"; import { Button } from "@/components/ui/button"; import { MobileShell } from "@/components/worker/MobileShell";
import { ApiError } from "@/lib/api";
import { createEnergyRecord } from "@/lib/api/energy"; import { getEvents } from "@/lib/api/events"; import { createFuelRecord } from "@/lib/api/fuel"; import { createWaterRecord } from "@/lib/api/water"; import { getEventZones } from "@/lib/api/zones";
import type { Event } from "@/types/event"; import type { EnergyRecordCreate, FuelRecordCreate, WaterRecordCreate } from "@/types/operations"; import type { Zone } from "@/types/zone";
export default function WorkerConsumptionPage() {
  const router = useRouter(); const params = useSearchParams(); const { toast } = useToast(); const [events, setEvents] = useState<Event[]>([]); const [eventId, setEventId] = useState(params.get("event_id") || ""); const [zones, setZones] = useState<Zone[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const eventData = await getEvents({ page: 1, limit: 100 }); const selected = eventId || eventData.items[0]?.id || ""; setEvents(eventData.items); setEventId(selected); setZones(selected ? await getEventZones(selected) : []); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar la informacion."); } finally { setLoading(false); } }, [eventId]);
  useEffect(() => { void load(); }, [load]);
  async function saveFuel(data: FuelRecordCreate) { if (!eventId) return; setSaving(true); try { await createFuelRecord(eventId, data); toast({ tone: "success", title: "Consumo registrado" }); router.push("/worker/mis-tareas"); } catch (e) { toast({ tone: "error", title: "No se pudo registrar", description: e instanceof ApiError ? e.detail : "Intenta nuevamente." }); } finally { setSaving(false); } }
  async function saveEnergy(data: EnergyRecordCreate) { if (!eventId) return; setSaving(true); try { await createEnergyRecord(eventId, data); toast({ tone: "success", title: "Consumo registrado" }); router.push("/worker/mis-tareas"); } catch (e) { toast({ tone: "error", title: "No se pudo registrar", description: e instanceof ApiError ? e.detail : "Intenta nuevamente." }); } finally { setSaving(false); } }
  async function saveWater(data: WaterRecordCreate) { if (!eventId) return; setSaving(true); try { await createWaterRecord(eventId, data); toast({ tone: "success", title: "Consumo registrado" }); router.push("/worker/mis-tareas"); } catch (e) { toast({ tone: "error", title: "No se pudo registrar", description: e instanceof ApiError ? e.detail : "Intenta nuevamente." }); } finally { setSaving(false); } }
  return <RoleGuard roles={["WORKER", "SUPERVISOR"]}><MobileShell title="Registrar consumo" description="Ingresa combustible, energia o agua desde terreno.">{loading ? <LoadingState label="Cargando eventos..." /> : null}{error ? <ErrorState message={error} onRetry={load} /> : null}{!loading && events.length === 0 ? <EmptyState title="Sin eventos" description="No tienes eventos disponibles." /> : null}{events.length > 0 ? <div className="space-y-4"><label className="grid gap-2 text-sm font-semibold">Evento<select className="h-12 rounded-2xl border px-4" value={eventId} onChange={(e) => setEventId(e.target.value)}>{events.map((e) => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><Link href={`/worker/subir-evidencia?event_id=${eventId}`}><Button className="w-full" variant="secondary"><Camera className="h-4 w-4" />Subir evidencia primero</Button></Link><MobileConsumptionForm loading={saving} zones={zones} onCancel={() => router.push("/worker/mis-tareas")} onEnergy={saveEnergy} onFuel={saveFuel} onWater={saveWater} /></div> : null}</MobileShell></RoleGuard>;
}
