export type EnvironmentalActionType = "ELECTRIC_LIGHTING_TOWER" | "ELECTRIC_MOTORCYCLE" | "ELECTRIC_CART" | "SOLAR_ENERGY" | "ELECTRIC_VEHICLE" | "BIKE_MOBILITY" | "PUBLIC_TRANSPORT" | "OTHER";
export type EnvironmentalActionStatus = "INCOMPLETE" | "READY_TO_CALCULATE" | "CALCULATED" | "MISSING_METHODOLOGY" | "NEEDS_REVIEW";
export type EnvironmentalMetricKey = "ENERGY_KWH" | "FUEL_AVOIDED_L" | "CO2E_BASELINE_KG" | "CO2E_ACTUAL_KG" | "CO2E_AVOIDED_KG" | "PM25_BASELINE_KG" | "PM25_ACTUAL_KG" | "PM25_AVOIDED_KG" | "PM10_BASELINE_KG" | "PM10_ACTUAL_KG" | "PM10_AVOIDED_KG" | "NOX_BASELINE_KG" | "NOX_ACTUAL_KG" | "NOX_AVOIDED_KG";

export type EnvironmentalMetric = { id: string; metric_key: EnvironmentalMetricKey; unit: string; calculated_value: string | null; reported_value: string | null; value: string | null; is_manual_override: boolean; override_reason?: string | null; calculation_method: string; calculated_at: string };
export type EnvironmentalAction = { id: string; event_id: string; session_id?: string | null; methodology_id?: string | null; action_type: EnvironmentalActionType; status: EnvironmentalActionStatus; name: string; description?: string | null; quantity_used: string; hours_used?: string | null; distance_km?: string | null; energy_kwh?: string | null; power_kw?: string | null; energy_source?: "MEASURED" | "CALCULATED" | "MANUAL" | null; notes?: string | null; created_by?: string | null; created_at: string; updated_at: string; metrics: EnvironmentalMetric[] };
export type EnvironmentalActionInput = { session_id?: string | null; methodology_id?: string | null; action_type: EnvironmentalActionType; name: string; description?: string; quantity_used: number; hours_used?: number; distance_km?: number; energy_kwh?: number; power_kw?: number; energy_source?: "MEASURED" | "MANUAL"; notes?: string };
export type EnvironmentalMethodology = { id: string; name: string; action_type: EnvironmentalActionType; baseline_technology: string; actual_technology: string; description: string; parameters: Record<string, unknown>; is_active: boolean; created_at?: string; updated_at?: string };
export type EnvironmentalFactor = { id: string; impact_type: string; technology: string; pollutant?: string | null; unit_basis: string; factor_value: string; factor_unit: string; source: string; source_url?: string | null; year: number; country?: string | null; methodology: string; is_active: boolean; created_at: string; updated_at: string };
export type EnvironmentalFactorInput = Omit<EnvironmentalFactor, "id" | "created_at" | "updated_at" | "is_active">;
export type EcoEquivalence = { id: string; key: string; name: string; metric_source: EnvironmentalMetricKey; factor: string; unit: string; source: string; year: number; is_active: boolean; created_at?: string; updated_at?: string };
export type EcoEquivalenceInput = Omit<EcoEquivalence, "id" | "created_at" | "updated_at" | "is_active">;
export type EnvironmentalSummary = { event_id: string; session_id?: string | null; actions_count: number; energy_kwh: string | null; fuel_avoided_l: string | null; co2e_avoided_kg: string | null; pm25_avoided_kg: string | null; pm10_avoided_kg: string | null; nox_avoided_kg: string | null; unavailable_metrics: EnvironmentalMetricKey[] };
