export type LogbookTemplateStatus="DRAFT"|"ACTIVE"|"ARCHIVED";
export type LogbookAssignmentStatus="PENDING"|"IN_PROGRESS"|"SUBMITTED"|"CHANGES_REQUESTED"|"RESUBMITTED"|"APPROVED"|"REJECTED"|"OVERDUE"|"CANCELLED";
export interface LogbookTemplate {id:string;name:string;description?:string;operational_stage:string;status:LogbookTemplateStatus;default_assignment_mode:"INDIVIDUAL"|"SHARED";default_client_visibility:boolean;created_at:string;updated_at:string;}
export interface LogbookVersion {id:string;template_id:string;version_number:number;status:"DRAFT"|"PUBLISHED"|"RETIRED";change_notes?:string;created_at:string;published_at?:string}
export interface LogbookTemplateDetail extends LogbookTemplate {versions:LogbookVersion[]}
export interface LogbookVersionDetail extends LogbookVersion {sections:LogbookSection[]}
export interface LogbookInstance {id:string;event_id:string;template_id:string;template_version_id:string;import_batch_id?:string;name:string;operational_stage:string;zone_id?:string;assignment_mode:"INDIVIDUAL"|"SHARED";opens_at?:string;due_at?:string;supervisor_id?:string;status:string;client_visibility:boolean;created_at:string;recurrence_series_id?:string;occurrence_date?:string;occurrence_modified:boolean;original_occurrence_date?:string}
export interface LogbookLifecycleSummary {run_id:string;started_at:string;finished_at:string;inspected_count:number;opened_count:number;overdue_count:number;skipped_count:number;failed_count:number;batch_count:number;series_inspected:number;occurrences_generated:number;series_failed:number}
export type LogbookRecurrenceFrequency="DAILY"|"WEEKLY"|"MONTHLY";
export type LogbookRecurrenceStatus="ACTIVE"|"PAUSED"|"FINISHED"|"CANCELLED";
export interface LogbookRecurrenceSeries {id:string;event_id:string;template_id:string;template_version_id:string;name:string;assignment_mode:"INDIVIDUAL"|"SHARED";supervisor_id?:string;client_visibility:boolean;frequency:LogbookRecurrenceFrequency;interval:number;weekdays?:number[];day_of_month?:number;start_date:string;end_mode:"END_DATE"|"COUNT";end_date?:string;max_occurrences?:number;opens_at_local:string;due_at_local:string;timezone:string;status:LogbookRecurrenceStatus;next_occurrence_date?:string;generated_count:number;revision:number;participant_ids:string[];occurrence_counts:Record<string,number>;created_at:string}
export interface LogbookRecurrencePayload {template_version_id:string;name?:string;zone_id?:string|null;assignment_mode:"INDIVIDUAL"|"SHARED";participant_ids:string[];supervisor_id?:string|null;client_visibility:boolean;frequency:LogbookRecurrenceFrequency;interval:number;weekdays?:number[];day_of_month?:number;start_date:string;end_mode:"END_DATE"|"COUNT";end_date?:string;max_occurrences?:number;opens_at_local:string;due_at_local:string;timezone:string}
export interface ClientLogbookSummary {id:string;event_id:string;name:string;operational_stage:string;status:string;completion_percentage:number;participation_percentage:number;approval_percentage:number;total_required_items:number;completed_items:number;failed_items:number;public_evidences:LogbookEvidence[]}
export interface LogbookAssignment {id:string;logbook_instance_id:string;user_id:string;status:LogbookAssignmentStatus;started_at?:string;submitted_at?:string;approved_at?:string;review_comment?:string;attempt_number:number;}
export interface LogbookOption {id:string;label:string;value:string;position:number;is_success_value:boolean;is_failure_value:boolean}
export interface LogbookEvidence {id:string;response_id:string;comment?:string;mime_type:string;file_size:number;original_filename:string;client_visible:boolean;created_at:string;deleted_at?:string}
export interface LogbookResponse {id:string;assignment_id:string;logbook_item_id:string;selected_option_id?:string;boolean_value?:boolean;numeric_value?:number;text_value?:string;is_not_applicable:boolean;result_status:"PENDING"|"COMPLETED"|"FAILED"|"NOT_APPLICABLE";comment?:string;version:number;evidences:LogbookEvidence[];completed_by_name?:string;corrective_incident_id?:string;corrective_task_id?:string}
export interface LogbookItem {id:string;title:string;description?:string;instructions?:string;position:number;item_type:"CHECKBOX"|"YES_NO"|"STATUS_SELECT"|"NUMBER"|"SHORT_TEXT"|"LONG_TEXT"|"PHOTO"|"CONFIRMATION";is_required:boolean;allow_not_applicable:boolean;evidence_policy:string;min_evidences:number;max_evidences:number;require_comment_on_failure:boolean;requires_supervisor_review:boolean;client_visible_by_default:boolean;creates_incident_suggestion:boolean;options:LogbookOption[]}
export interface LogbookSection {id:string;title:string;description?:string;position:number;is_required:boolean;items:LogbookItem[]}
export interface LogbookInstanceDetail {id:string;event_id:string;event_name:string;import_batch_id?:string;name:string;operational_stage:string;status:string;assignment_mode:"INDIVIDUAL"|"SHARED";version:{id:string;version_number:number;sections:LogbookSection[]};assignments:Array<LogbookAssignment&{responses:LogbookResponse[];user_name?:string;history:Array<{id:string;action:string;previous_status?:string;new_status:string;comment?:string;attempt_number:number;created_at:string}>}>;metrics:{completion_percentage:number;participation_percentage:number;approval_percentage:number;total_participants:number;pending:number;in_progress:number;submitted:number;changes_requested:number;approved:number;total_required_items:number;completed_items:number;failed_items:number;collaborating_participants:number}}
export interface LogbookTemplateCreate {name:string;description?:string;instructions?:string;operational_stage:string;default_assignment_mode:"INDIVIDUAL"|"SHARED";default_client_visibility:boolean;sections:Array<{title:string;position:number;is_required:boolean;items:Array<{title:string;position:number;item_type:string;is_required:boolean;allow_not_applicable?:boolean;evidence_policy:string;min_evidences:number;max_evidences:number;require_comment_on_failure?:boolean;options:unknown[]}>}>}
export interface LogbookImportIssue {code:string;message:string;row?:number;column?:number;value?:string}
export interface LogbookImportPreview {filename:string;file_sha256:string;sheet_name?:string;activities_count:number;dates_count:number;scheduled_items_count:number;instances_to_create:number;date_range?:{from:string;to:string};warnings:LogbookImportIssue[];errors:LogbookImportIssue[];days:Array<{date:string;activities:Array<{source_row:number;title:string}>}>}
export interface LogbookContributionEvidence {id:string;contribution_id:string;uploaded_by?:string;mime_type:string;file_size:number;original_filename:string;created_at:string;deleted_at?:string}
export interface LogbookContribution {id:string;instance_item_id:string;assignment_id:string;author_id:string;author_name?:string;description:string;version:number;created_at:string;updated_at:string;evidences:LogbookContributionEvidence[]}
export interface LogbookInstanceItem {id:string;instance_id:string;title:string;source_row:number;position:number;contributions:LogbookContribution[]}
export interface DailyLogbookMetrics {total_activities:number;activities_without_contributions:number;activities_with_contributions:number;contributions_count:number;participants_assigned:number;participants_contributed:number;evidences_count:number;completion_percentage:number}
