export type LogbookTemplateStatus="DRAFT"|"ACTIVE"|"ARCHIVED";
export type LogbookAssignmentStatus="PENDING"|"IN_PROGRESS"|"SUBMITTED"|"CHANGES_REQUESTED"|"RESUBMITTED"|"APPROVED"|"REJECTED"|"OVERDUE"|"CANCELLED";
export interface LogbookTemplate {id:string;name:string;description?:string;operational_stage:string;status:LogbookTemplateStatus;default_assignment_mode:"INDIVIDUAL"|"SHARED";default_client_visibility:boolean;created_at:string;updated_at:string;}
export interface LogbookVersion {id:string;template_id:string;version_number:number;status:"DRAFT"|"PUBLISHED"|"RETIRED";change_notes?:string;created_at:string;published_at?:string}
export interface LogbookTemplateDetail extends LogbookTemplate {versions:LogbookVersion[]}
export interface LogbookVersionDetail extends LogbookVersion {sections:LogbookSection[]}
export interface LogbookInstance {id:string;event_id:string;template_id:string;template_version_id:string;name:string;operational_stage:string;zone_id?:string;assignment_mode:"INDIVIDUAL"|"SHARED";opens_at?:string;due_at?:string;supervisor_id?:string;status:string;client_visibility:boolean;created_at:string}
export interface ClientLogbookSummary {id:string;event_id:string;name:string;operational_stage:string;status:string;completion_percentage:number;participation_percentage:number;approval_percentage:number;total_required_items:number;completed_items:number;failed_items:number;public_evidences:LogbookEvidence[]}
export interface LogbookAssignment {id:string;logbook_instance_id:string;user_id:string;status:LogbookAssignmentStatus;started_at?:string;submitted_at?:string;approved_at?:string;review_comment?:string;attempt_number:number;}
export interface LogbookOption {id:string;label:string;value:string;position:number;is_success_value:boolean;is_failure_value:boolean}
export interface LogbookEvidence {id:string;response_id:string;comment?:string;mime_type:string;file_size:number;original_filename:string;client_visible:boolean;created_at:string;deleted_at?:string}
export interface LogbookResponse {id:string;assignment_id:string;logbook_item_id:string;selected_option_id?:string;boolean_value?:boolean;numeric_value?:number;text_value?:string;is_not_applicable:boolean;result_status:"PENDING"|"COMPLETED"|"FAILED"|"NOT_APPLICABLE";comment?:string;version:number;evidences:LogbookEvidence[];completed_by_name?:string;corrective_incident_id?:string;corrective_task_id?:string}
export interface LogbookItem {id:string;title:string;description?:string;instructions?:string;position:number;item_type:"CHECKBOX"|"YES_NO"|"STATUS_SELECT"|"NUMBER"|"SHORT_TEXT"|"LONG_TEXT"|"PHOTO"|"CONFIRMATION";is_required:boolean;allow_not_applicable:boolean;evidence_policy:string;min_evidences:number;max_evidences:number;require_comment_on_failure:boolean;requires_supervisor_review:boolean;client_visible_by_default:boolean;creates_incident_suggestion:boolean;options:LogbookOption[]}
export interface LogbookSection {id:string;title:string;description?:string;position:number;is_required:boolean;items:LogbookItem[]}
export interface LogbookInstanceDetail {id:string;event_id:string;event_name:string;name:string;operational_stage:string;status:string;assignment_mode:"INDIVIDUAL"|"SHARED";version:{id:string;version_number:number;sections:LogbookSection[]};assignments:Array<LogbookAssignment&{responses:LogbookResponse[];user_name?:string;history:Array<{id:string;action:string;previous_status?:string;new_status:string;comment?:string;attempt_number:number;created_at:string}>}>;metrics:{completion_percentage:number;participation_percentage:number;approval_percentage:number;total_participants:number;pending:number;in_progress:number;submitted:number;changes_requested:number;approved:number;total_required_items:number;completed_items:number;failed_items:number;collaborating_participants:number}}
export interface LogbookTemplateCreate {name:string;description?:string;instructions?:string;operational_stage:string;default_assignment_mode:"INDIVIDUAL"|"SHARED";default_client_visibility:boolean;sections:Array<{title:string;position:number;is_required:boolean;items:Array<{title:string;position:number;item_type:string;is_required:boolean;allow_not_applicable?:boolean;evidence_policy:string;min_evidences:number;max_evidences:number;require_comment_on_failure?:boolean;options:unknown[]}>}>}
