"use client";

import { Users } from "lucide-react";
import { useEffect, useState } from "react";

import { ModalShell } from "@/components/common/ModalShell";
import { useToast } from "@/components/common/ToastProvider";
import { Button } from "@/components/ui/button";
import { previewImportBatchParticipants, previewImportBatchSupervisor, updateImportBatchParticipants, updateImportBatchSupervisor } from "@/lib/api/logbooks";
import { getEventStaff } from "@/lib/api/staff";
import { logbookError } from "@/lib/logbook-errors";
import type { EventStaff } from "@/types/staff";
import type { LogbookBulkParticipantOperation, LogbookBulkParticipantsPayload, LogbookBulkParticipantsPreview, LogbookBulkParticipantScope, LogbookBulkSupervisorPreview } from "@/types/logbook";

export function LogbookImportBatchEditor({batchId,eventId,dates,onDone}:{batchId:string;eventId:string;dates:string[];onDone:()=>Promise<void>}) {
  const {toast}=useToast();
  const [open,setOpen]=useState(false); const [staff,setStaff]=useState<EventStaff[]>([]);
  const [operation,setOperation]=useState<LogbookBulkParticipantOperation>("ADD");
  const [scope,setScope]=useState<LogbookBulkParticipantScope>("ALL");
  const [participants,setParticipants]=useState<string[]>([]); const [selectedDates,setSelectedDates]=useState<string[]>([]);
  const [preview,setPreview]=useState<LogbookBulkParticipantsPreview|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(open)void getEventStaff(eventId).then(setStaff).catch(cause=>setError(logbookError(cause,"No se pudieron cargar los participantes.")));},[eventId,open]);
  const payload:LogbookBulkParticipantsPayload={operation,scope,participant_ids:participants,dates:scope==="DATES"?selectedDates:[]};
  const valid=participants.length>0&&(scope!=="DATES"||selectedDates.length>0);
  function resetPreview(){setPreview(null);setError("");}
  async function analyze(){if(!valid||busy)return;setBusy(true);setError("");try{setPreview(await previewImportBatchParticipants(batchId,payload));}catch(cause){setError(logbookError(cause,"No se pudo calcular el cambio masivo."));}finally{setBusy(false);}}
  async function apply(){if(!preview||busy)return;setBusy(true);setError("");try{const result=await updateImportBatchParticipants(batchId,payload);toast({title:"Participantes actualizados",description:`${result.instances_matched} bitácoras modificadas.`,tone:"success"});setOpen(false);setPreview(null);setParticipants([]);setSelectedDates([]);await onDone();}catch(cause){setError(logbookError(cause,"No se pudo aplicar el cambio masivo."));}finally{setBusy(false);}}
  return <><Button onClick={()=>setOpen(true)} size="sm" variant="secondary"><Users className="mr-1 h-4 w-4"/>Editar participantes del lote</Button><SupervisorBatchEditor batchId={batchId} dates={dates} eventId={eventId} onDone={onDone}/>{open?<ModalShell title="Editar participantes del lote" description="Aplica el mismo cambio a las bitácoras creadas en esta importación." onClose={()=>{if(!busy)setOpen(false)}}><div className="max-h-[75vh] space-y-4 overflow-y-auto">
    <label className="grid gap-1 text-sm">Operación<select className="rounded-xl border p-2" value={operation} onChange={e=>{setOperation(e.target.value as LogbookBulkParticipantOperation);resetPreview();}}><option value="ADD">Agregar participantes</option><option value="REMOVE">Quitar participantes</option><option value="REPLACE">Reemplazar participantes</option></select></label>
    <label className="grid gap-1 text-sm">Aplicar a<select className="rounded-xl border p-2" value={scope} onChange={e=>{setScope(e.target.value as LogbookBulkParticipantScope);resetPreview();}}><option value="ALL">Todas las bitácoras del lote</option><option value="FUTURE">Solo bitácoras futuras</option><option value="DATES">Fechas seleccionadas</option></select></label>
    {scope==="DATES"?<fieldset className="max-h-40 overflow-y-auto rounded-xl border p-3"><legend className="text-sm font-medium">Fechas</legend>{dates.map(date=><label className="mt-2 flex gap-2 text-sm" key={date}><input checked={selectedDates.includes(date)} onChange={e=>{setSelectedDates(current=>e.target.checked?[...current,date]:current.filter(value=>value!==date));resetPreview();}} type="checkbox"/>{new Date(`${date}T12:00:00`).toLocaleDateString("es-CL", { timeZone: "America/Santiago" })}</label>)}</fieldset>:null}
    <fieldset className="max-h-64 overflow-y-auto rounded-xl border p-3"><legend className="text-sm font-medium">Participantes</legend>{staff.filter(member=>!["CLIENT","ADMIN","SUPER_ADMIN"].includes(member.user?.role||"")).map(member=><label className="mt-2 flex gap-2 text-sm" key={member.user_id}><input checked={participants.includes(member.user_id)} onChange={e=>{setParticipants(current=>e.target.checked?[...current,member.user_id]:current.filter(id=>id!==member.user_id));resetPreview();}} type="checkbox"/>{member.user?.full_name||member.user_id}</label>)}</fieldset>
    {!preview?<Button disabled={!valid||busy} onClick={()=>void analyze()}>{busy?"Calculando…":"Revisar impacto"}</Button>:<div className="space-y-3 rounded-xl bg-slate-50 p-3 text-sm"><p><strong>{preview.instances_matched}</strong> bitácoras afectadas</p><p>{preview.assignments_to_add} asignaciones nuevas · {preview.assignments_to_remove} retiros · {preview.assignments_preserved} sin cambios</p>{preview.historical_assignments_preserved?<p className="rounded bg-amber-50 p-2 text-amber-800">{preview.historical_assignments_preserved} asignaciones tienen actividad histórica: sus aportes y evidencias se conservarán.</p>:null}<Button disabled={busy} onClick={()=>void apply()}>{busy?"Aplicando…":"Confirmar cambio masivo"}</Button><Button disabled={busy} onClick={()=>setPreview(null)} variant="secondary">Volver y editar</Button></div>}
    {error?<p className="rounded bg-red-50 p-2 text-sm text-red-700">{error}</p>:null}<Button disabled={busy} onClick={()=>setOpen(false)} variant="secondary">Cerrar</Button>
  </div></ModalShell>:null}</>;
}

function SupervisorBatchEditor({batchId,eventId,dates,onDone}:{batchId:string;eventId:string;dates:string[];onDone:()=>Promise<void>}) {
  const {toast}=useToast(); const [open,setOpen]=useState(false); const [staff,setStaff]=useState<EventStaff[]>([]); const [supervisor,setSupervisor]=useState("");
  const [scope,setScope]=useState<LogbookBulkParticipantScope>("ALL"); const [selectedDates,setSelectedDates]=useState<string[]>([]); const [preview,setPreview]=useState<LogbookBulkSupervisorPreview|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(open)void getEventStaff(eventId).then(setStaff).catch(cause=>setError(logbookError(cause)));},[eventId,open]);
  const payload={supervisor_id:supervisor||null,scope,dates:scope==="DATES"?selectedDates:[]}; const valid=scope!=="DATES"||selectedDates.length>0;
  async function analyze(){if(!valid||busy)return;setBusy(true);setError("");try{setPreview(await previewImportBatchSupervisor(batchId,payload));}catch(cause){setError(logbookError(cause));}finally{setBusy(false);}}
  async function apply(){if(!preview||busy)return;setBusy(true);setError("");try{const result=await updateImportBatchSupervisor(batchId,payload);toast({title:"Supervisor actualizado",description:`${result.instances_to_update} bitácoras modificadas.`,tone:"success"});setOpen(false);setPreview(null);await onDone();}catch(cause){setError(logbookError(cause));}finally{setBusy(false);}}
  return <><Button onClick={()=>setOpen(true)} size="sm" variant="secondary">Editar supervisor del lote</Button>{open?<ModalShell title="Editar supervisor del lote" description="Configura el supervisor por alcance y conserva las bitácoras cerradas." onClose={()=>!busy&&setOpen(false)}><div className="max-h-[75vh] space-y-4 overflow-y-auto"><label className="grid gap-1 text-sm">Supervisor<select className="rounded-xl border p-2" value={supervisor} onChange={event=>{setSupervisor(event.target.value);setPreview(null);}}><option value="">Sin supervisor</option>{staff.filter(member=>member.user?.role==="SUPERVISOR").map(member=><option key={member.user_id} value={member.user_id}>{member.user?.full_name||member.user_id}</option>)}</select></label><label className="grid gap-1 text-sm">Aplicar a<select className="rounded-xl border p-2" value={scope} onChange={event=>{setScope(event.target.value as LogbookBulkParticipantScope);setPreview(null);}}><option value="ALL">Todas las bitácoras editables</option><option value="FUTURE">Solo bitácoras futuras</option><option value="DATES">Fechas seleccionadas</option></select></label>{scope==="DATES"?<fieldset className="max-h-44 overflow-y-auto rounded-xl border p-3"><legend className="text-sm font-medium">Fechas</legend>{dates.map(date=><label className="mt-2 flex gap-2 text-sm" key={date}><input checked={selectedDates.includes(date)} onChange={event=>{setSelectedDates(current=>event.target.checked?[...current,date]:current.filter(value=>value!==date));setPreview(null);}} type="checkbox"/>{new Date(`${date}T12:00:00`).toLocaleDateString("es-CL",{timeZone:"America/Santiago"})}</label>)}</fieldset>:null}{preview?<div className="rounded-xl bg-slate-50 p-3 text-sm"><p>{preview.instances_to_update} por actualizar · {preview.instances_unchanged} sin cambios · {preview.instances_locked} bloqueadas</p><Button className="mt-3" disabled={busy} onClick={()=>void apply()}>Confirmar cambio</Button></div>:<Button disabled={!valid||busy} onClick={()=>void analyze()}>Revisar impacto</Button>}{error?<p className="text-sm text-red-700">{error}</p>:null}</div></ModalShell>:null}</>;
}
