"use client";
import { zodResolver } from "@hookform/resolvers/zod"; import { useForm } from "react-hook-form"; import { z } from "zod";
import { ModalShell } from "@/components/common/ModalShell"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input";
import type { WaterRecordCreate } from "@/types/operations"; import type { Zone } from "@/types/zone";
const schema = z.object({ water_source: z.string().min(1), volume_m3: z.coerce.number().min(0.01), zone_id: z.string().optional(), notes: z.string().optional() });
export function WaterRecordFormModal({ zones, loading, onClose, onSubmit }: { zones: Zone[]; loading?: boolean; onClose: () => void; onSubmit: (data: WaterRecordCreate) => Promise<void> }) {
  const { register, handleSubmit } = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema), defaultValues: { water_source: "NETWORK" } });
  return <ModalShell title="Registrar agua" onClose={onClose}><form className="space-y-4" onSubmit={handleSubmit((v) => onSubmit({ ...v, zone_id: v.zone_id || null, notes: v.notes || null }))}><label className="grid gap-2 text-sm font-semibold">Fuente<select className="h-12 rounded-2xl border px-4" {...register("water_source")}><option>NETWORK</option><option>TRUCK</option><option>BOTTLED</option><option>REUSED</option><option>OTHER</option></select></label><label className="grid gap-2 text-sm font-semibold">m3<Input type="number" step="0.01" {...register("volume_m3")} /></label><label className="grid gap-2 text-sm font-semibold">Zona<select className="h-12 rounded-2xl border px-4" {...register("zone_id")}><option value="">Sin zona</option>{zones.map((z) => <option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Notas<Input {...register("notes")} /></label><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={loading}>Guardar</Button></div></form></ModalShell>;
}
