const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const tab = fs.readFileSync(path.join(root, "components/environmental-impact/EnvironmentalImpactTab.tsx"), "utf8");
const form = fs.readFileSync(path.join(root, "components/environmental-impact/EnvironmentalActionForm.tsx"), "utf8");
const api = fs.readFileSync(path.join(root, "lib/api/environmental.ts"), "utf8");
const eventTabs = fs.readFileSync(path.join(root, "components/events/EventTabs.tsx"), "utf8");
const catalog = fs.readFileSync(path.join(root, "app/(dashboard)/admin/impacto-ambiental/page.tsx"), "utf8");
const routes = fs.readFileSync(path.join(root, "lib/routes.ts"), "utf8");

assert.match(eventTabs, /Impacto Ambiental/);
assert.match(tab, /No calculado/);
assert.match(tab, /Factor o metodología pendiente/);
assert.match(tab, /LoadingState/);
assert.match(tab, /ErrorState/);
assert.match(tab, /ConfirmDialog/);
assert.match(tab, /updateEnvironmentalAction/);
assert.match(tab, /setFormAction\(item\)/);
assert.doesNotMatch(tab + form, /window\.(alert|confirm)/);
assert.match(form, /ELECTRIC_LIGHTING_TOWER/);
assert.match(form, /ELECTRIC_MOTORCYCLE/);
assert.match(form, /scope === "SHOW"/);
assert.match(form, /Potencia promedio por equipo/);
assert.match(api, /environmental-impact\/summary/);
assert.match(api, /environmental-actions/);
assert.match(routes, /\/admin\/impacto-ambiental/);
assert.match(catalog, /RoleGuard roles=\{\["SUPER_ADMIN", "ADMIN"\]\}/);
assert.match(catalog, /Factores/);
assert.match(catalog, /Metodolog/);
assert.match(catalog, /Equivalencias/);
assert.match(catalog, /no constituyen compensaciones/);
assert.doesNotMatch(catalog, /window\.(alert|confirm)/);
assert.match(api, /createEnvironmentalFactor/);
assert.match(api, /updateEnvironmentalMethodology/);
assert.match(api, /createEnvironmentalEquivalence/);
console.log("environmental impact UI contract passed");
