const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const tab = fs.readFileSync(path.join(root, "components/environmental-impact/EnvironmentalImpactTab.tsx"), "utf8");
const form = fs.readFileSync(path.join(root, "components/environmental-impact/EnvironmentalActionForm.tsx"), "utf8");
const detail = fs.readFileSync(path.join(root, "components/environmental-impact/EnvironmentalActionDetail.tsx"), "utf8");
const api = fs.readFileSync(path.join(root, "lib/api/environmental.ts"), "utf8");
const eventTabs = fs.readFileSync(path.join(root, "components/events/EventTabs.tsx"), "utf8");
const catalog = fs.readFileSync(path.join(root, "app/(dashboard)/admin/impacto-ambiental/page.tsx"), "utf8");
const routes = fs.readFileSync(path.join(root, "lib/routes.ts"), "utf8");
const migration = fs.readFileSync(path.join(root, "../backend/alembic/versions/20260821_0052_environmental_per_unit_energy.py"), "utf8");

assert.match(eventTabs, /Impacto Ambiental/);
assert.match(tab, /No calculado/);
assert.match(tab, /Factor o metodología pendiente/);
assert.match(tab, /LoadingState/);
assert.match(tab, /ErrorState/);
assert.match(tab, /ConfirmDialog/);
assert.match(tab, /updateEnvironmentalAction/);
assert.match(tab, /setFormAction\(item\)/);
assert.match(tab, /summary\.equivalences/);
assert.match(tab, /No representan compensaciones ni certificaciones ambientales/);
assert.match(tab, /source_value/);
assert.match(tab, /Alcance mostrado/);
assert.match(tab, /getEnvironmentalSummary\(eventId, selectedSession\)/);
assert.match(tab, /getEnvironmentalActions\(eventId, selectedSession\)/);
assert.match(tab, /PM10 evitado/);
assert.match(tab, /NOx evitado/);
assert.match(tab, /EnvironmentalActionDetail/);
assert.match(detail, /Comparación ambiental/);
assert.match(detail, /Factores congelados en el cálculo/);
assert.match(detail, /Fórmula aplicada/);
assert.doesNotMatch(detail, /window\.(alert|confirm)/);
assert.doesNotMatch(tab + form, /window\.(alert|confirm)/);
assert.match(form, /ELECTRIC_LIGHTING_TOWER/);
assert.match(form, /ELECTRIC_MOTORCYCLE/);
assert.match(form, /scope === "SHOW"/);
assert.match(form, /Energía de 1 torre por hora \(kWh\)/);
assert.match(form, /EcoEvent calculará automáticamente la energía total/);
assert.match(form, /energy_per_unit_hour_kwh/);
assert.match(form, /energy_input_mode = "PER_UNIT_HOUR"/);
assert.match(form, /Number\(energy\) \* Number\(quantity\) \* Number\(hours\)/);
assert.match(form, /Energía total calculada/);
assert.match(form, /torres ×/);
assert.match(form, /Equivale a/);
assert.match(form, /Torre fotovoltaica/);
assert.match(detail, /Energía generada/);
assert.match(detail, /Diésel evitado/);
assert.match(detail, /Cálculo energético/);
assert.match(detail, /historicalTowerTotal/);
assert.match(detail, /action\.energy_input_mode === "PER_UNIT_HOUR"/);
assert.match(detail, /torres ×/);
assert.match(tab, /Energía generada/);
assert.match(tab, /Diésel evitado/);
assert.match(migration, /Torre diésel vs torre fotovoltaica/);
assert.match(form, /normalizedDecimal/);
assert.match(form, /replace\(\/\(\\\.\\d\*\?\[1-9\]\)0\+\$\|\\\.0\+\$\//);
assert.match(api, /environmental-impact\/summary/);
assert.match(api, /environmental-actions/);
assert.match(routes, /\/admin\/impacto-ambiental/);
assert.match(catalog, /RoleGuard roles=\{\["SUPER_ADMIN", "ADMIN"\]\}/);
assert.match(catalog, /Factores/);
assert.match(catalog, /Metodolog/);
assert.match(catalog, /Equivalencias/);
assert.match(catalog, /no constituyen compensaciones/);
assert.doesNotMatch(catalog, /window\.(alert|confirm)/);
assert.match(api, /createEnvironmentalFactor/);
assert.match(api, /updateEnvironmentalMethodology/);
assert.match(api, /createEnvironmentalEquivalence/);
console.log("environmental impact UI contract passed");
