import {api} from "@/lib/api";
import type {ListResponse} from "@/types/common";
import type {ClientLogbookSummary,LogbookAssignment,LogbookInstance,LogbookInstanceDetail,LogbookResponse,LogbookEvidence,LogbookTemplate,LogbookTemplateCreate,LogbookTemplateDetail,LogbookVersion,LogbookVersionDetail} from "@/types/logbook";
export const getLogbookTemplates=(status?:string)=>api.get<ListResponse<LogbookTemplate>>(`/logbook-templates${status?`?status=${status}`:""}`);
export const createLogbookTemplate=(data:LogbookTemplateCreate)=>api.post<LogbookTemplate>("/logbook-templates",data);
export const getLogbookTemplate=(id:string)=>api.get<LogbookTemplateDetail>(`/logbook-templates/${id}`);
export const publishLogbookVersion=(id:string)=>api.post<LogbookVersion>(`/logbook-versions/${id}/publish`);
export const archiveLogbookTemplate=(id:string)=>api.post<LogbookTemplate>(`/logbook-templates/${id}/archive`);
export const updateLogbookTemplate=(id:string,data:Partial<LogbookTemplateCreate>)=>api.patch<LogbookTemplate>(`/logbook-templates/${id}`,data);
export const createLogbookVersion=(id:string,sourceVersionId?:string)=>api.post<LogbookVersion>(`/logbook-templates/${id}/versions${sourceVersionId?`?source_version_id=${sourceVersionId}`:""}`);
export const getLogbookVersion=(id:string)=>api.get<LogbookVersionDetail>(`/logbook-versions/${id}`);
export const getMyLogbooks=(status?:string)=>api.get<LogbookAssignment[]>(`/me/logbooks${status?`?status=${status}`:""}`);
export const submitLogbook=(id:string)=>api.post<LogbookAssignment>(`/logbook-assignments/${id}/submit`);
export const approveLogbook=(id:string,comment?:string)=>api.post<LogbookAssignment>(`/logbook-assignments/${id}/approve`,{comment});
export const requestLogbookChanges=(id:string,comment:string)=>api.post<LogbookAssignment>(`/logbook-assignments/${id}/request-changes`,{comment});
export const createLogbookIncident=(responseId:string,data:Record<string,unknown>)=>api.post(`/logbook-responses/${responseId}/incident`,data);
export const createCorrectiveTask=(responseId:string,data:Record<string,unknown>)=>api.post(`/logbook-responses/${responseId}/corrective-task`,data);
export const getLogbookInstance=(id:string)=>api.get<LogbookInstanceDetail>(`/logbook-instances/${id}`);
export const getEventLogbooks=(eventId:string,filters?:{status?:string;template_id?:string;stage?:string})=>{const query=new URLSearchParams(Object.entries(filters||{}).filter(([,value])=>Boolean(value)) as string[][]).toString();return api.get<{items:LogbookInstance[];total:number;page:number;limit:number}>(`/events/${eventId}/logbooks${query?`?${query}`:""}`)};
export const createEventLogbook=(eventId:string,data:Record<string,unknown>)=>api.post<LogbookInstance>(`/events/${eventId}/logbooks`,data);
export const openLogbookInstance=(id:string)=>api.post<LogbookInstance>(`/logbook-instances/${id}/open`);
export const cancelLogbookInstance=(id:string,reason:string)=>api.post<LogbookInstance>(`/logbook-instances/${id}/cancel`,{reason});
export const getClientLogbook=(id:string)=>api.get<ClientLogbookSummary>(`/client/logbooks/${id}`);
export const saveLogbookResponse=(assignmentId:string,data:Record<string,unknown>)=>api.put<LogbookResponse>(`/logbook-assignments/${assignmentId}/responses`,data);
export const clearLogbookResponse=(assignmentId:string,itemId:string,version:number)=>api.delete<LogbookResponse>(`/logbook-assignments/${assignmentId}/responses/${itemId}?version=${version}`);
export const uploadLogbookEvidence=(assignmentId:string,responseId:string,file:File,comment?:string)=>{const body=new FormData();body.append("file",file);if(comment)body.append("comment",comment);return api.post<LogbookEvidence>(`/logbook-assignments/${assignmentId}/responses/${responseId}/evidences`,body)};
export const getLogbookEvidenceAccess=(id:string)=>api.get<{url:string;expires_in:number}>(`/logbook-evidences/${id}/access`);
export const deleteLogbookEvidence=(id:string)=>api.delete<void>(`/logbook-evidences/${id}`);
export const addLogbookParticipants=(id:string,userIds:string[])=>api.post<LogbookAssignment[]>(`/logbook-instances/${id}/participants`,{user_ids:userIds});
export const removeLogbookParticipant=(instanceId:string,assignmentId:string)=>api.delete<void>(`/logbook-instances/${instanceId}/participants/${assignmentId}`);
