"use client";
import { useCallback, useEffect, useState } from "react"; import { Plus } from "lucide-react";
import { ErrorState } from "@/components/common/ErrorState"; import { LoadingState } from "@/components/common/LoadingState"; import { PageHeader } from "@/components/common/PageHeader"; import { RoleGuard } from "@/components/layout/RoleGuard"; import { Button } from "@/components/ui/button"; import { CarbonFactorDeleteDialog } from "@/components/carbon/CarbonFactorDeleteDialog"; import { CarbonFactorFormModal } from "@/components/carbon/CarbonFactorFormModal"; import { CarbonFactorTable } from "@/components/carbon/CarbonFactorTable";
import { createCarbonFactor, deleteCarbonFactor, getCarbonFactors, updateCarbonFactor } from "@/lib/api/carbonFactors"; import type { CarbonFactor, CarbonFactorCreate, CarbonFactorUpdate } from "@/types/carbon";
export default function CarbonFactorsPage() {
  const [factors, setFactors] = useState<CarbonFactor[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [formFactor, setFormFactor] = useState<CarbonFactor | null | undefined>(); const [deleting, setDeleting] = useState<CarbonFactor | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const data = await getCarbonFactors({ page: 1, limit: 100 }); setFactors(data.items); } catch (e) { setError(e instanceof Error ? e.message : "El catalogo de factores de emision aun no esta disponible en el backend."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(data: CarbonFactorCreate | CarbonFactorUpdate) { setSaving(true); try { if (formFactor) await updateCarbonFactor(formFactor.id, data); else await createCarbonFactor(data as CarbonFactorCreate); setFormFactor(undefined); await load(); } finally { setSaving(false); } }
  async function confirmDelete() { if (!deleting) return; await deleteCarbonFactor(deleting.id); setDeleting(null); await load(); }
  return <RoleGuard roles={["SUPER_ADMIN", "ADMIN"]}><div className="space-y-6"><PageHeader title="Factores de emision" description="Catalogo de factores para calcular huella de carbono." actions={<Button onClick={() => setFormFactor(null)}><Plus className="h-4 w-4" />Crear factor</Button>} />{loading ? <LoadingState label="Cargando factores..." /> : null}{error ? <ErrorState message={error} onRetry={load} /> : null}{!loading && !error ? <CarbonFactorTable factors={factors} onDelete={setDeleting} onEdit={setFormFactor} /> : null}{formFactor !== undefined ? <CarbonFactorFormModal factor={formFactor} loading={saving} onClose={() => setFormFactor(undefined)} onSubmit={save} /> : null}<CarbonFactorDeleteDialog factor={deleting} onClose={() => setDeleting(null)} onConfirm={confirmDelete} /></div></RoleGuard>;
}
